/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package BloodBankManagement;


import java.sql.SQLException;

import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Souleymane
 */
public class AddingBloodtoStock extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddingBloodtoStock
     */
    public AddingBloodtoStock() {
        initComponents();
    }
    Connection con;
    PreparedStatement insert;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstname = new javax.swing.JTextField();
        Qty = new javax.swing.JTextField();
        sex = new javax.swing.JComboBox<>();
        bloodtype = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        middle = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        none = new javax.swing.JLabel();
        collectorID = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();
        Addd = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dob1 = new de.wannawork.jcalendar.JCalendarComboBox();
        dateCollection = new de.wannawork.jcalendar.JCalendarComboBox();
        dateExpiration = new de.wannawork.jcalendar.JCalendarComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 330, 40));
        jPanel1.add(Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 250, 90, 30));

        sex.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Male", "Female" }));
        jPanel1.add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 130, 30));

        bloodtype.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bloodtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel1.add(bloodtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 250, 120, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Blood Type:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 120, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Middle");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 100, 120, 30));
        jPanel1.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 330, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Donor Sex:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 120, 30));
        jPanel1.add(middle, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 330, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date of Birth:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 120, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Title");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 60, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lastname");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 120, 30));

        none.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dornor Informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(none, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 1320, 310));

        collectorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectorIDActionPerformed(evt);
            }
        });
        jPanel1.add(collectorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 270, 40));
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 230, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Firstname");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 120, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Collector's ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 120, 30));
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 450, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Full name");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 100, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Collection Date:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 140, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Expiration Date:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 140, 30));

        Clear.setBackground(new java.awt.Color(255, 255, 0));
        Clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Clear.setText("Clear");
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 750, 120, 40));

        Addd.setBackground(new java.awt.Color(0, 204, 51));
        Addd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Addd.setForeground(new java.awt.Color(255, 255, 255));
        Addd.setText("Add");
        Addd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdddActionPerformed(evt);
            }
        });
        jPanel1.add(Addd, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 750, 120, 40));

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 0, 51));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 750, 120, 40));

        label.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Blood to Stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, 1364, 837));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Collector Informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 1320, 310));

        dob1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(dob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 200, 30));

        dateCollection.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(dateCollection, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 200, 30));

        dateExpiration.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(dateExpiration, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 562, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void collectorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collectorIDActionPerformed

    private void AdddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdddActionPerformed
        // TODO add your handling code here:
        // Ensure you get the date as a string from the DatePicker
            Date date = dob1.getDate();
            Date date1 = dateCollection.getDate();
            Date date2 = dateExpiration.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dateofbirth = (date != null) ? sdf.format(date) : null;  // Format the date to a string, or set it to null

            // Get all fields data
            String first = firstname.getText();
            String last = lastname.getText();
            String middlename = middle.getText();
            String gend = sex.getSelectedItem().toString();
            String blood = bloodtype.getSelectedItem().toString();
            String quantity = Qty.getText();
            
            //col info
             String collectorIDn = collectorID.getText();
             String collTitle = title.getText();
             String collectorFull = fullname.getText();
             
             String dateofCollection = (date1 != null) ? sdf.format(date1) : null;
             String dateofExpiration = (date2 != null) ? sdf.format(date2) : null;
             

            

            try {
                // Establish connection
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con = DriverManager.getConnection(
                    "jdbc:sqlserver://bloodbankdata.database.windows.net:1433;database=bloodBank;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;",
                    "csiadmin", "7ousRespo3!");

                // Check if connection is successful
                if (con != null) {
                    System.out.println("Database connection established.");
                } else {
                    System.out.println("Failed to establish database connection.");
                    return; // Exit if connection fails
                }

                // Prepare the SQL query
                String insertQuery = "INSERT INTO Inventory ( Firstname, Lastname, middleName, DonorSex, BloodType, dateOfBirth, CollectionDate, ExpirationDate, Quantity, Title, CollectorID, collectedBy) " +
                                     "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                

                // Prepare the statement
                insert = con.prepareStatement(insertQuery);
                if (insert != null) {
                    System.out.println("Prepared statement created successfully.");
                } else {
                    System.out.println("Failed to create prepared statement.");
                    return; // Exit if preparation fails
                }

                // Set the parameters in the correct order
                insert.setString(1, first);
                insert.setString(2, last);
                insert.setString(3, middlename);
                insert.setString(4, gend );  // Formatted date string
                insert.setString(5, blood);
                insert.setString(6, dateofbirth);
                insert.setString(7, dateofCollection);  // Make sure the State field is set correctly
                insert.setString(8, dateofExpiration);   // Make sure the City field is set correctly
                insert.setString(9, quantity);    // Zip field
                insert.setString(10, collTitle );       // Telephone field
                insert.setString(11, collectorIDn); // Email field
                insert.setString(12, collectorFull );
                
                
                // Execute the query
                int k = insert.executeUpdate();

                // Check the result and provide feedback
                if (k == 1) {
                    JOptionPane.showMessageDialog(this, " added successfully!");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add.");
                }

            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Driver not found: " + ex.getMessage());
                Logger.getLogger(ConnectData.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
                Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_AdddActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_ExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addd;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField Qty;
    private javax.swing.JComboBox<String> bloodtype;
    private javax.swing.JTextField collectorID;
    private de.wannawork.jcalendar.JCalendarComboBox dateCollection;
    private de.wannawork.jcalendar.JCalendarComboBox dateExpiration;
    private de.wannawork.jcalendar.JCalendarComboBox dob1;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField middle;
    private javax.swing.JLabel none;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
