/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package BloodBankManagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Souleymane.Sono
 */
public class DeleteDonor extends javax.swing.JInternalFrame {

    /**
     * Creates new form UpdateDonor
     */
    public DeleteDonor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        last1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        first = new javax.swing.JLabel();
        last = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        middle = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        place = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bloodtype = new javax.swing.JLabel();
        addr = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        zip = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        tel = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        last1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N

        setBackground(new java.awt.Color(204, 51, 0));
        setClosable(true);
        setIconifiable(true);
        setTitle("Delete Donor");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Donor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 18))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(817, 1200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(239, 245, 250));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 15))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel4.setText("Donor ID or Lastname:*");

        searchField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        searchField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 47, 750, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 65, 780, 740));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel7.setText("Firstname:*");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 98, 27));

        first.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        first.setText("0");
        getContentPane().add(first, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 110, 188, 36));

        last.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        last.setText("00000");
        getContentPane().add(last, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 188, 36));

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel14.setText("Lastname:*");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 98, 27));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel8.setText("Middle Name:*");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 100, 27));

        middle.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        middle.setText("000000");
        getContentPane().add(middle, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, 140, 36));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel9.setText("Date of Birth:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 247, 104, 40));

        dob.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        dob.setText("000000");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 250, 188, 36));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel5.setText("Sex:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, 59, 27));

        gender.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        gender.setText("000000");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 290, 115, 36));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel6.setText("Place of Birth:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, 108, 27));

        place.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        place.setText("000000");
        getContentPane().add(place, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 330, 169, 36));

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel10.setText("Address:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, -1, 27));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel12.setText("City:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 43, 27));

        jLabel28.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel28.setText("Email:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 58, 27));

        jLabel29.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel29.setText("Telephone:");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 75, 27));

        jLabel30.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel30.setText("Blood Type");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, 75, 27));

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel11.setText("State:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 410, 43, 27));

        bloodtype.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        bloodtype.setText("000000");
        getContentPane().add(bloodtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 260, 36));

        addr.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        addr.setText("000000");
        getContentPane().add(addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 370, 280, 36));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel13.setText("Zip:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 400, 43, 27));

        zip.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        zip.setText("000000");
        getContentPane().add(zip, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 390, 115, 36));

        state.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        state.setText("000000");
        getContentPane().add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 400, 115, 36));

        city.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        city.setText("000000");
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, 115, 36));

        email.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        email.setText("000000");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 280, 36));

        tel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        tel.setText("000000");
        getContentPane().add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 490, 260, 36));

        clear.setBackground(new java.awt.Color(51, 255, 0));
        clear.setFont(new java.awt.Font("Bahnschrift", 0, 19)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 750, 112, 34));

        delete.setBackground(new java.awt.Color(255, 51, 0));
        delete.setFont(new java.awt.Font("Bahnschrift", 0, 19)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 750, 112, 34));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Donor Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 610, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        PreparedStatement search = null;
        ResultSet rs = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbankdata", "root", "root");

            String query = "SELECT * FROM registration WHERE idRegistration = ? OR lastname = ?";
            String donorValue = searchField.getText();  // Corrected typo from `searchFiedl` to `searchField`
            search = con.prepareStatement(query);
            search.setString(1, donorValue);
            search.setString(2, donorValue);

            rs = search.executeQuery();

            if (rs.next()) {
                // Populate fields with the found donor's data
                first.setText(rs.getString("firstname"));
                last.setText(rs.getString("lastname"));
                middle.setText(rs.getString("middlename"));
                gender.setText(rs.getString("gender"));
                bloodtype.setText(rs.getString("bloodtype"));
                addr.setText(rs.getString("address"));
                city.setText(rs.getString("city"));
                dob.setText(rs.getString("dob"));
                // Uncomment email field if needed: email.setText(rs.getString("email"));

                JOptionPane.showMessageDialog(this, "Donor Found");
            } else {
                JOptionPane.showMessageDialog(this, "Donor not Found");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DBconnect.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DeleteDonor.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            // Close resources in reverse order of opening
            try {
                if (rs != null) rs.close();
                if (search != null) search.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                Logger.getLogger(DeleteDonor.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this donor?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
    
    // Proceed only if the user clicks "Yes"
    if (confirm == JOptionPane.YES_OPTION) {
        Connection con = null;
        PreparedStatement deleteStmt = null;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbankdata", "root", "root");
            
            String query = "DELETE FROM registration WHERE idRegistration = ? OR lastname = ?";
            String donorValue = searchField.getText();  // Get input from searchField
            deleteStmt = con.prepareStatement(query);
            deleteStmt.setString(1, donorValue);
            deleteStmt.setString(2, donorValue);
            
            int rowsAffected = deleteStmt.executeUpdate();
            
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Donor deleted successfully.");
                // Optionally clear fields after deletion
                first.setText("");
                last.setText("");
                middle.setText("");
                gender.setText("");
                bloodtype.setText("");
                addr.setText("");
                city.setText("");
                dob.setText("");
                // Clear other fields if needed
            } else {
                JOptionPane.showMessageDialog(this, "Donor not found. Deletion failed.");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DBconnect.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DeleteDonor.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            // Close resources to prevent memory leaks
            try {
                if (deleteStmt != null) deleteStmt.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                Logger.getLogger(DeleteDonor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    } else {
        // User selected "No," so we skip the deletion process
        JOptionPane.showMessageDialog(this, "Deletion cancelled.");
    }
        
        
        
        
        
    }//GEN-LAST:event_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addr;
    private javax.swing.JLabel bloodtype;
    private javax.swing.JLabel city;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel email;
    private javax.swing.JLabel first;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel last;
    private javax.swing.JLabel last1;
    private javax.swing.JLabel middle;
    private javax.swing.JLabel place;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel state;
    private javax.swing.JLabel tel;
    private javax.swing.JLabel zip;
    // End of variables declaration//GEN-END:variables
}
