/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package BloodBankManagement;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;





/**
 *
 * @author Souleymane.Sono
 */
public class DonorMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form DonorMenu
     */
    private JTable donorList;
    public DonorMenu() {
        //jScrollPane1.setVisible(false);
        initComponents();
        //DonorPane.setVisible(true);
        //donorList = new JTable();
       //DefaultTableModel model = new DefaultTableModel(
        //        new Object[]{"Blood ID", "Full Name", "Date of Birth", "Sex", "BloodType", "Email"},
         //       0
        //);
       // donorList.setModel(model);
        //jScrollPane1.setViewportView(donorList);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        AddDonor = new javax.swing.JButton();
        UpdateDonor = new javax.swing.JButton();
        RemoveDonor = new javax.swing.JButton();
        ShowList = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        DonorPane = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Donor Menu");
        setFocusable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 960, 100, 30));

        AddDonor.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        AddDonor.setForeground(new java.awt.Color(153, 0, 0));
        AddDonor.setIcon(new javax.swing.ImageIcon("C:\\Users\\Souleymane\\Downloads\\Current\\BloodBankProject-master\\src\\resources\\icons\\plus.png")); // NOI18N
        AddDonor.setText("Add New Donor");
        AddDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDonorActionPerformed(evt);
            }
        });
        getContentPane().add(AddDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 30));

        UpdateDonor.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        UpdateDonor.setForeground(new java.awt.Color(153, 0, 0));
        UpdateDonor.setIcon(new javax.swing.ImageIcon("C:\\Users\\Souleymane\\Downloads\\Current\\BloodBankProject-master\\src\\resources\\icons\\time.png")); // NOI18N
        UpdateDonor.setText("update Donor Info");
        UpdateDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDonorActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        RemoveDonor.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        RemoveDonor.setForeground(new java.awt.Color(153, 0, 0));
        RemoveDonor.setIcon(new javax.swing.ImageIcon("C:\\Users\\Souleymane\\Downloads\\Current\\BloodBankProject-master\\src\\resources\\icons\\ready.png")); // NOI18N
        RemoveDonor.setText("Remove Donor");
        RemoveDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveDonorActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 200, 30));

        ShowList.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        ShowList.setForeground(new java.awt.Color(153, 0, 0));
        ShowList.setIcon(new javax.swing.ImageIcon("C:\\Users\\Souleymane\\Downloads\\Current\\BloodBankProject-master\\src\\resources\\icons\\score.jpg")); // NOI18N
        ShowList.setText("Show Donor list");
        ShowList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowListActionPerformed(evt);
            }
        });
        getContentPane().add(ShowList, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 210, 40));

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "More", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 420, 220));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 170, 170));

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Donor Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 437, 990));

        jButton6.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 0, 0));
        jButton6.setText("see Report");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 160, 30));

        DonorPane.setAutoscrolls(true);
        DonorPane.setFocusable(false);
        getContentPane().add(DonorPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 1510, 970));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Souleymane\\Downloads\\Current\\BloodBankProject-master\\src\\resources\\pngegg (28).png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 290, 300));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 1520, 990));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1990, 1060));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Connection getConnection() throws SQLException {
        String url = "jdbc:sqlserver://bloodbankdata.database.windows.net:1433;"
                   + "database=bloodBank;"
                   + "user=csiadmin@bloodbankdata;"
                   + "password=7ousRespo3!;"
                   + "encrypt=true;"
                   + "trustServerCertificate=false;"
                   + "hostNameInCertificate=*.database.windows.net;"
                   + "loginTimeout=30;";

        // Establish connection
        return DriverManager.getConnection(url);
    }
    
    private void retrieveAllData() {
        //jScrollPane1.setVisible(true);
        String query = "SELECT " +
                "CONCAT(i.Firstname, ' ', i.Lastname) AS full_name, " +
                "i.DonorID, " +
                "i.DateOfBirth, " +
                "i.Sex, " +
                "i.BloodType, " +
                "i.Email " +
                "FROM Registration i";

        

        try (Connection con = getConnection();
             PreparedStatement pstmt = con.prepareStatement(query);
             ResultSet rs = pstmt.executeQuery()) {

            DefaultTableModel tableModel = (DefaultTableModel) donorList.getModel();
            tableModel.setRowCount(0); // Clear the table before adding rows

            while (rs.next()) {
                String DonorID = rs.getString("DonorID");
                String fullName = rs.getString("full_name");
                String bloodType = rs.getString("Sex");
                String collectionDate = rs.getString("DateOfBirth");
                String collectedBy = rs.getString("BloodType");
                String expirationDate = rs.getString("Email");

                tableModel.addRow(new Object[]{DonorID, fullName, bloodType, collectionDate, collectedBy, expirationDate});
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException("Error retrieving all data: " + ex.getMessage());
            
           
        }
    }
    
    
    
    private void AddDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDonorActionPerformed
        // TODO add your handling code here:
        //jScrollPane1.setVisible(false);
        AppLogger.logInfo("Add Button Performed  at " + java.time.LocalDateTime.now());
        Registration reg = new Registration();
        DonorPane.add(reg).setVisible(true);
        
        
        
        
    }//GEN-LAST:event_AddDonorActionPerformed
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         AppLogger.logInfo("Closed at  " + java.time.LocalDateTime.now());
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UpdateDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDonorActionPerformed
        // TODO add your handling code here:
        //jScrollPane1.setVisible(false);
        UpdateDonorInfo ud = new UpdateDonorInfo();
        DonorPane.add(ud).setVisible(true);
        AppLogger.logInfo("Donor Information Upadted  " + java.time.LocalDateTime.now());
        
    }//GEN-LAST:event_UpdateDonorActionPerformed

    private void RemoveDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveDonorActionPerformed
        // TODO add your handling code here:
        //jScrollPane1.setVisible(false);
        DeleteDonor dd = new DeleteDonor();
        DonorPane.add(dd).setVisible(true);
        AppLogger.logInfo("Donor Removed at " + java.time.LocalDateTime.now());
    }//GEN-LAST:event_RemoveDonorActionPerformed

    private void ShowListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowListActionPerformed
        // TODO add your handling code here:
        jScrollPane1.setVisible(true);
        donorList = new JTable();
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Blood ID", "Full Name", "Date of Birth", "Sex", "BloodType", "Email"},
                0
        );
        donorList.setModel(model);
        jScrollPane1.setViewportView(donorList);
        
       
        DonorPane.setVisible(false);
        retrieveAllData();
        AppLogger.logInfo("Viewed List of Donors at  " + java.time.LocalDateTime.now());
    }//GEN-LAST:event_ShowListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDonor;
    private javax.swing.JLabel DonorPane;
    private javax.swing.JButton RemoveDonor;
    private javax.swing.JButton ShowList;
    private javax.swing.JButton UpdateDonor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
