/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BloodBankManagement;

/**
 *
 * @author Souleymane.Sono
 */
public class LabelPane extends javax.swing.JFrame {

    /**
     * Creates new form LabelPane
     */
    public LabelPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelToPrint = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        BloodClass = new javax.swing.JLabel();
        BloodTypeField = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelToPrint.setBackground(new java.awt.Color(249, 249, 249));
        PanelToPrint.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        PanelToPrint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelToPrint.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 914, 59, 51));

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel15.setText("Collection Date    |       Unit Number         |       Expires");
        PanelToPrint.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 610, 60));

        jLabel29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PanelToPrint.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 190, 40));

        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PanelToPrint.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 190, 40));

        jLabel30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PanelToPrint.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 190, 40));

        jLabel28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PanelToPrint.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 260, 370));

        BloodClass.setFont(new java.awt.Font("Arial", 1, 300)); // NOI18N
        BloodClass.setText("A");
        PanelToPrint.add(BloodClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 230, 260));

        BloodTypeField.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        BloodTypeField.setText("Rh Positive");
        PanelToPrint.add(BloodTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 200, 40));

        jLabel31.setFont(new java.awt.Font("Bahnschrift", 1, 30)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("CPDA -1 Whole Blood");
        PanelToPrint.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 350, 90));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Approx :");
        PanelToPrint.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 140, 50));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel16.setText("See Circular Information for indication,  ");
        PanelToPrint.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 330, 60));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel17.setText("Contraindications caution and Methods of Infusion");
        PanelToPrint.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 330, 40));

        jLabel32.setFont(new java.awt.Font("Bahnschrift", 1, 30)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("VOLUNTEER DONOR");
        PanelToPrint.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 340, 50));

        jLabel33.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel33.setText("This Product may transmit Infectious Agents");
        PanelToPrint.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 330, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Volunteer Name:");
        PanelToPrint.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 140, 50));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setText("Collected by:");
        PanelToPrint.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, 140, 50));

        jLabel34.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PanelToPrint.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 630, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelToPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelToPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabelPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabelPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabelPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabelPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabelPane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloodClass;
    private javax.swing.JLabel BloodTypeField;
    private javax.swing.JPanel PanelToPrint;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    // End of variables declaration//GEN-END:variables
}
